# File: .github/workflows/setup-node/action.yml
name: setup-node
description: "Setup Node.js - Cache dependencies - Install dependencies"
runs:
  using: "composite"
  steps:
    # Setup a Node v20 build environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Cache npm packages for speeding up the next step
    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    # Install npm packages
    - name: Install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci